In [8]:
import pandas as pd
import numpy as np
import seaborn as sns

In [9]:
k = [4,2.56789,9,87.999,40,'hyderabadd']

In [10]:
k

[4, 2.56789, 9, 87.999, 40, 'hyderabadd']

In [11]:
pd.Series(k)  #it convert all the elements if there is one string of a float

0             4
1       2.56789
2             9
3        87.999
4            40
5    hyderabadd
dtype: object

In [12]:
a = np.random.randint(20,50,(5,4))

In [13]:
a

array([[40, 34, 44, 26],
       [30, 36, 43, 42],
       [30, 25, 39, 20],
       [44, 30, 29, 24],
       [33, 40, 32, 27]])

In [14]:
a.ndim

2

In [15]:
pd.Series(a)  #Series work only in one dimension array not more then it

ValueError: Data must be 1-dimensional, got ndarray of shape (5, 4) instead

In [17]:
b = np.random.randint(20,50,15)

In [18]:
b

array([45, 46, 27, 21, 27, 40, 21, 35, 38, 38, 24, 26, 36, 40, 23])

In [20]:
s=pd.Series(b)

In [21]:
s

0     45
1     46
2     27
3     21
4     27
5     40
6     21
7     35
8     38
9     38
10    24
11    26
12    36
13    40
14    23
dtype: int32

In [22]:
s[4]

27

In [23]:
s[4:15:2]

4     27
6     21
8     38
10    24
12    36
14    23
dtype: int32

In [24]:
c = np.random.randint(100,200,(6,5))

In [25]:
c

array([[127, 180, 180, 122, 148],
       [159, 121, 138, 162, 160],
       [119, 153, 167, 104, 111],
       [168, 100, 192, 106, 126],
       [146, 166, 118, 189, 122],
       [141, 178, 159, 102, 101]])

In [26]:
c.ndim

2

In [27]:
c.shape

(6, 5)

In [31]:
df = pd.DataFrame(c) #DataFrame is used to work with the 2nd dimension array 

In [32]:
df

0    1    2    3    4
0  127  180  180  122  148
1  159  121  138  162  160
2  119  153  167  104  111
3  168  100  192  106  126
4  146  166  118  189  122
5  141  178  159  102  101

In [37]:
df = pd.DataFrame(c,columns=['roll','name','age','country','state'])  #we can give the columns name also with our own

In [38]:
df

roll  name  age  country  state
0   127   180  180      122    148
1   159   121  138      162    160
2   119   153  167      104    111
3   168   100  192      106    126
4   146   166  118      189    122
5   141   178  159      102    101

In [39]:
df = pd.DataFrame(c,columns=['roll','name','age','country','state'], index = [11,22,33,44,55,66])  #index for rows

In [40]:
df

roll  name  age  country  state
11   127   180  180      122    148
22   159   121  138      162    160
33   119   153  167      104    111
44   168   100  192      106    126
55   146   166  118      189    122
66   141   178  159      102    101

In [44]:
df.iloc[0] #accessing the valuse by index

roll       127
name       180
age        180
country    122
state      148
Name: 11, dtype: int32

In [45]:
df.loc[11] #accessing the values by roms name

roll       127
name       180
age        180
country    122
state      148
Name: 11, dtype: int32

In [46]:
df.iloc[0,0]

127

In [47]:
df.loc[11,'age']

180

In [48]:
df.loc[11,['name','age']]

name    180
age     180
Name: 11, dtype: int32

In [51]:
df.iloc[0,1:3]

name    180
age     180
Name: 11, dtype: int32

In [50]:
df

roll  name  age  country  state
11   127   180  180      122    148
22   159   121  138      162    160
33   119   153  167      104    111
44   168   100  192      106    126
55   146   166  118      189    122
66   141   178  159      102    101

In [54]:
df.iloc[[3,4]]

roll  name  age  country  state
44   168   100  192      106    126
55   146   166  118      189    122

In [57]:
df.loc[[22,55]]

roll  name  age  country  state
22   159   121  138      162    160
55   146   166  118      189    122

In [60]:
df.age

11    180
22    138
33    167
44    192
55    118
66    159
Name: age, dtype: int32

In [61]:
df['age']

11    180
22    138
33    167
44    192
55    118
66    159
Name: age, dtype: int32

In [62]:
df[['name','age']]

name  age
11   180  180
22   121  138
33   153  167
44   100  192
55   166  118
66   178  159

In [65]:
df.loc[[22,55],['age','name']]

age  name
22  138   121
55  118   166

In [66]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [69]:
sns.load_dataset('tips')

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]